### ISSUE TITLE
Loading Firmware / waiting for Com Port

### ISSUE THREAD

**Issue by Urs4410** [dlktdr/HeadTracker#101]
Hi
Started the Firmware upload, but it possible cannot connect to the Com Port, the Arduno is Flashing orange, therefore waiting to get something (if I am right)
I am running Win 10 pro

**Comment by dlktdr** [comment]
Can you send the log

**Comment by dlktdr** [comment]
Can you check in device manager, it should show up as a COM port.

If not try double tapping the white button on the board and see if it comes up as a com port then. That should put it in bootloader mode where the orange light pulses slowly on slowly off. If that works, try double tapping it as soon as it says. Waiting for comport in the GUI

**Comment by Urs4410** [comment]
I don't see the com port and even in the GUI it does not say Waiting for comport, after double tapping the white button
I will quickly reboot the machine -- let you know whether this would help

**Comment by Urs4410** [comment]
there is no change, even after re-boot
no Com visible in the device manager, no reaction in Gui - no: waiting for comport

**Comment by dlktdr** [comment]
Hmm if it's not showing a COM port in device manager even after you double tap the white button, either you have a bad USB cord. Maybe try another one. Or maybe the drivers on that system aren't installed correctly. Open Zadig https://zadig.akeo.ie/ and see what's listed, choose list all devices from the menu to see it.

This is what should be shown after double tapping the white button. See what driver is loaded.
![image](https://user-images.githubusercontent.com/281145/177890521-d94a19da-cef9-4f07-83d4-8a70dfda3afd.png)

**Comment by Urs4410** [comment]
First I would like to thank you for your patience - hope my English had not been too bad, since I am Swiss (German speaking).
Never the less -- it had been the cable. I tried at least 5 different cable, until I got one which worked. I even don't know with which device I got this.
Thanks again
