### ISSUE TITLE
Better more clear content on the IMU output - Local Board

### ISSUE THREAD

**Issue by kobelev-tech** [dlktdr/HeadTracker#111]
The panel should look like:
![image](https://user-images.githubusercontent.com/90671453/183277598-14d1d568-8567-4188-8642-ab39e2797a20.png)

1. On the left there should be the raw values in angular degrees as they are reported by the IMU unit.
2. After that there should gain sliders showing how these graduses are amplified.
3. Next column should show what comes to in the terms of the width of the pulses.
4. Reverse check-boxes should be centered under the column title.

**Comment by dlktdr** [comment]
I do like this idea, changed the wording. Raw Value (Grad) is too long. Value and the degree symbol will get the point across.

See #112
