### ISSUE TITLE
Version in diagnostics always 0.42

### ISSUE THREAD

**Issue by SilentZen** [dlktdr/HeadTracker#14]
Version in diagnostics always shows 0.42 on tested 0.5 and 0.6.

**Comment by dlktdr** [comment]
Oops.. forgot to change it in the FW file on the last two. I'll update them.

I'm going to write up a procedure for releasing updates so I don't forget an area to update from now on.

**Comment by dlktdr** [comment]
Bins have been updated with proper version numbers
