### ISSUE TITLE
Possibility to have 16 channel over Bluetooth

### ISSUE THREAD

**Issue by pierrotm777** [dlktdr/HeadTracker#148]
Hello,

For the first time, i can command my camera with my HT.
I use a TX16S MkII with Frsky PARA module and a Nano Ble .
If i understand, in BT mode it's not possible to use channel after channel 8.
That would be possible to add the possibility to have 16 channels in BT mode or it's only for PPM and SBUS ?

Cordially,

Pierre

**Comment by dlktdr** [comment]
Long time for a response, sorry. But no not officially. Would have to customize the code on both ends to make it happen. 

On OpenTX/EdgeTx radios it's possible to remap the channels as you see fit at the radio end. Needing more than 8 is usually unlikely from this Headtracker.

https://headtracker.gitbook.io/head-tracker-v2.2/radio-setup/open-edge-tx/color-screen-radios/tx16s-example

**Comment by pierrotm777** [comment]
Ok, so just remap tr1, tr2 and tr3 to channel really used by the camera.
Thanks for your help.
Pierre
