### ISSUE TITLE
No red "calibration sphere" in V0.7

### ISSUE THREAD

**Issue by kevin-kevjan** [dlktdr/HeadTracker#15]
performed calibration, but no visual red 'calibration sphere' for feedback..
After awhile "Gaps" did go low enough "Save" button was made active.

![Screenshot 2021-02-10 215946](https://user-images.githubusercontent.com/65918321/107598373-894ddc80-6beb-11eb-856c-b7b7b3200815.jpg)

**Comment by dlktdr** [comment]
Well at least it still worked even though the visualization didn't show.

Try to fix a "TLS initialization" from missing SSL libs and now probably can't find the GLUT .dll now.

I'll look into it.

**Comment by dlktdr** [comment]
Please try again on 0.71.

**Comment by kevin-kevjan** [comment]
Just tried 0.71. Same issue of no mag visualization.

(I no longer get TLS error however after loading VS Redistributable)

![Screenshot 2021-02-13 130437](https://user-images.githubusercontent.com/65918321/107857380-19fb0700-6dfc-11eb-8509-e94a9d082881.jpg)

**Comment by dlktdr** [comment]
Could you check if you have the following files in your windows folder?
C:\windows\system32\glu32.dll
C:\windows\system32\opengl32.dll

**Comment by kevin-kevjan** [comment]
Yes. I do have both those files in my Win\sys32 directory. (one noted below)

Also, I checked on my other laptop (that never had the TLS error) and the red visualization does work correctly on that system.....so it is dependent on this laptop. 

![Screenshot 2021-02-13 154548](https://user-images.githubusercontent.com/65918321/107861337-56862d00-6e13-11eb-9099-fccb32ce00a4.jpg)

**Comment by dlktdr** [comment]
Ok that's good those are supposed to come with Windows.

Try that google drive link above if you can, and cross your fingers :)

**Comment by kevin-kevjan** [comment]
Success!  ....**Yes** the version 0.71_custom did show the visualization.

![Screenshot 2021-02-13 162521](https://user-images.githubusercontent.com/65918321/107862100-68b69a00-6e18-11eb-864a-2d2232c45f97.jpg)

**Comment by dlktdr** [comment]
Awesome.. Thanks again for testing all these.. I'll make this change permanent in the new ones.

**Comment by kevin-kevjan** [comment]
Happy to help…..This is a very cool project and perfect timing for me and several friends looking for easy FPV head trackers.

**Comment by dlktdr** [comment]
Released 0.72 Gui with fix
