### ISSUE TITLE
Win32 app

### ISSUE THREAD

**Issue by Shortcircuitboards** [dlktdr/HeadTracker#156]
Hy,

I´m using a old transformer Laptop as Fieldequipment. But it just runs Win32 bit.

Is there any chance to get the Headtracker app as Win32 Version?

Thanks

**Comment by dlktdr** [comment]
Sorry for delay, unfortunately it's not super easy to get a win32 version of the code anymore. Since we updated to QT6, they don't provide binaries for 32bit anymore. Would have to compile QT yourself, then the project. It's doable, just not as easy :)
