### ISSUE TITLE
Futaba 8FG - PPM - can't use channel after 8

### ISSUE THREAD

**Issue by jerem94000** [dlktdr/HeadTracker#158]
Hello

For the Arduino HeadTracker, i would need to use Channel 10, 11 and 12.
To do this, I need to activate "12CH" for the trainer in the 8FG radio.
But as soon as I  switch "8CH" to "12CH" on the Trainer, I can note receive anymore correctly the signal from the Arduino, which directly appears to its max.

Do you know why ?

Thanks in advance :-).

![Futaba Servo](https://github.com/dlktdr/HeadTracker/assets/143118991/dd3aef67-0c09-4f6a-a542-b787f7ce0ffc)
![Futaba Trainer - 12CH](https://github.com/dlktdr/HeadTracker/assets/143118991/85a493e2-a879-4385-85ed-c79a3d2880e2)

**Comment by rotorman** [comment]
See: https://www.rcgroups.com/forums/showpost.php?p=31693706&postcount=6285

**Comment by jerem94000** [comment]
Aahh ... thank you for this link.
I didn't succeed to find any information on this subject.

Indeed, To be able use more than 8 channels in the 8FG : 
- I set in the Radio : MLT2 for the frequency
- and in the Trainer configuration : 12CH

And when I activate the trainer swith on the radio, it capts a signal ... but the 3 channels (10, 11 and 12) direclty go to the max and totally not react to the move of the Arduino.

**Comment by rotorman** [comment]
Get a hold to a scope or a logic analyzer. Then put your Futaba into 12 channel trainer mode as student radio and capture and post the signal. We can extract from that the timing difference to "normal" 8 channel PPM pulses.

**Comment by jerem94000** [comment]
> Get a hold to a scope or a logic analyzer. 

Could you please give me a link which shows me what is this scope ?
Thank you :-)

**Comment by rotorman** [comment]
Something like this (or similar): https://www.tek.com/en/products/oscilloscopes

**Comment by jerem94000** [comment]
Ah yes of course.
I already used it ... 30 yeas ago, when I was in high school !!
A bit expensive  for me this test...

**Comment by rotorman** [comment]
You do not need to buy it. Just find someone who has oscilloscope, or even better a logic analyzer, like e.g. Saleae, and then ask to use it for 5 minutes.

**Comment by dlktdr** [comment]
> Aahh ... thank you for this link. I didn't succeed to find any information on this subject.
> 
> Indeed, To be able use more than 8 channels in the 8FG :
> 
> * I set in the Radio : MLT2 for the frequency
> * and in the Trainer configuration : 12CH
> 
> But when I activate the trainer switch on the radio, it capts a signal ... but the 3 channels (10, 11 and 12) direclty go to the max and totally not react to the move of the Arduino (as we can see on the first copy screen upper.
> 
> Strange not find other posts talking about this subjet. I may not be the first to want to use channel above Channel 8 ... moreover if we want to use Pan + Tilt + Roll.

Did you also increase the channel count of the PPM output in the GUI?  Since there are 12 channels you may need to also increase the frame lenght.
![image](https://github.com/dlktdr/HeadTracker/assets/281145/24c2336d-0920-4fbb-9c4b-d990d6d17975)
