### ISSUE TITLE
Version listed in Firware update.

### ISSUE THREAD

**Issue by kevin-kevjan** [dlktdr/HeadTracker#16]
Just downloaded and installed V0.72 using Win10 system that had prior TLS error and no calibration visualization

**ALL GOOD now.** 👍 

However, firmware download list did not show V.72 (although GUI did) but all worked as expected for V0.72

![Screenshot 2021-02-14 164243](https://user-images.githubusercontent.com/65918321/107889910-c9f76f80-6ee3-11eb-9a66-5c45d06e0163.jpg)

**Comment by dlktdr** [comment]
My plan was if you have a .7x firmware it will work with any .7x GUI. Any minor fixes to either the GUI or firmware version would go up by .01, so no I didn't post a 0.72 firmware, 0.71 is the newest. I guess I can see how this could be confusing.

Maybe I'll switch the numbering scheme to be completely different. then just grab the newest available.

I think it's getting stable enough I can call it 1.0 pretty soon, maybe I'll switch it up then.

**Comment by kevin-kevjan** [comment]
Good to go….minimal confusion and will simply resolve itself as next version is released.

Working is working!
