### ISSUE TITLE
only short bluetooth connection

### ISSUE THREAD

**Issue by TheFoxy** [dlktdr/HeadTracker#160]
if i try to connect  bluetooth to TX16s  following serial output and only a short connection - why?

Connected to COM7
Trying to connect to NANO33BLE 
GUI: {"Cmd":"FW"}� 
Connected to a NANO33BLE 
GUI: {"Cmd":"Get"}� 
HT: i (3.648) main: Sending Settings 
GUI: {"Cmd":"RD","btaddr":true,"btcon":true,"btrmt":true,"panoff":true,"panout":true,"rolloff":true,"rollout":true,"tiltoff":true,"tiltout":true,"trpenabled":true}�P 
HT: i (4.456) main: Data Added/Remove 
HT: i (10.235) main: Bluetooth connected :) 
HT: i (10.236) main: Connected to Address A0:B7:65:4A:AD:AA (public) 
HT: i (10.236) main: PHY Connection Rx:1M TX:1M 
HT: i (10.236) main: Requesting coded PHY - Success 
HT: i (10.320) main: Bluetooth PHY Updated. RxPHY:� TxPHY:� 
HT: i (10.335) main: Bluetooth Params Request. IntMax:10 IntMin:10 Lat:0 Timeout:70 
HT: i (10.453) main: Bluetooth Params Updated. Int:10 Lat:0 Timeout:70 
HT: w (12.28) main: Bluetooth disconnected (reason 8) 
HT: i (145.578) main: Bluetooth connected :) 
HT: i (145.578) main: Connected to Address A0:B7:65:4A:AD:AA (public) 
HT: i (145.578) main: PHY Connection Rx:1M TX:1M 
HT: i (145.579) main: Requesting coded PHY - Success 
HT: i (145.660) main: Bluetooth PHY Updated. RxPHY:� TxPHY:� 
HT: i (145.675) main: Bluetooth Params Request. IntMax:10 IntMin:10 Lat:0 Timeout:70 
HT: i (145.793) main: Bluetooth Params Updated. Int:10 Lat:0 Timeout:70 
HT: w (147.368) main: Bluetooth disconnected (reason 8) 
HT: i (160.260) main: Bluetooth connected :) 
HT: i (160.261) main: Connected to Address A0:B7:65:4A:AD:AA (public) 
HT: i (160.261) main: PHY Connection Rx:1M TX:1M 
HT: i (160.261) main: Requesting coded PHY - Success 
HT: i (160.352) main: Bluetooth PHY Updated. RxPHY:� TxPHY:� 
HT: i (160.367) main: Bluetooth Params Request. IntMax:10 IntMin:10 Lat:0 Timeout:70 
HT: i (160.485) main: Bluetooth Params Updated. Int:10 Lat:0 Timeout:70 
HT: w (162.60) main: Bluetooth disconnected (reason 8) 
HT: i (289.584) main: Bluetooth connected :) 
HT: i (289.584) main: Connected to Address A0:B7:65:4A:AD:AA (public) 
HT: i (289.584) main: PHY Connection Rx:1M TX:1M 
HT: i (289.584) main: Requesting coded PHY - Success 
HT: i (289.669) main: Bluetooth PHY Updated. RxPHY:� TxPHY:� 
HT: i (289.684) main: Bluetooth Params Request. IntMax:10 IntMin:10 Lat:0 Timeout:70 
HT: i (289.802) main: Bluetooth Params Updated. Int:10 Lat:0 Timeout:70 
HT: w (291.377) main: Bluetooth disconnected (reason 8)

**Comment by dlktdr** [comment]
Looks like it's possibly something to do with the coded connection request. What BT module is in your TX16s?
