### ISSUE TITLE
ABX00069Drift problems

### ISSUE THREAD

**Issue by tianbin4729** [dlktdr/HeadTracker#161]
When using ABX00069, I found that rapid movement can cause yaw axis drift, which often occurs. Moreover, ABX00069 cannot perform mag calibration。

**Comment by dlktdr** [comment]
I have some work here I think there is a change affecting newer versions for some.

Not sure about the mag calibration. If you check the box for use Magnetometer in the box here 
![image](https://github.com/dlktdr/HeadTracker/assets/281145/c9753d57-52c2-4928-8592-f962145d5f41)
close the calibration window and check under diagnostic display, do you see the sensor responding
![image](https://github.com/dlktdr/HeadTracker/assets/281145/9a990574-e4f4-49c0-81e1-b6cacd829c28)

**Comment by tianbin4729** [comment]
![image](https://github.com/dlktdr/HeadTracker/assets/156054199/c4916785-12c6-4595-b7eb-d9c39fd6d4cf)
![image](https://github.com/dlktdr/HeadTracker/assets/156054199/2bb485ed-f360-4eb1-b745-c4d6e12e5cb6)
The data of magx magy has not changed
