### ISSUE TITLE
Windows 11 support

### ISSUE THREAD

**Issue by bxrogers** [dlktdr/HeadTracker#163]
The graph at the bottom is not viewable.  I have no idea whether the sensor are working .  I did a calibration, but couldn’t tell if it helped or hurt.

all the fonts seem huge.  It reminds me of trying to open windows 95 apps in windows 10.  

is this normal? 

I’m on the latest version…

********************
Update: I ran the app as admin, and then the graph was not collapsed and the sliders started moving

**Comment by dlktdr** [comment]
![image](https://github.com/dlktdr/HeadTracker/assets/281145/17eeb924-2899-49b2-b215-965729f9da05)

How it looks for me on Win 11. Nothing too out of place. Your using v2.2 and not a very old one?

Can you post a screenshot too.

**Comment by dlktdr** [comment]
Closing for lack of feedback
