### ISSUE TITLE
Unable to determine board type moving from GUI .72 to .90

### ISSUE THREAD

**Issue by kevin-kevjan** [dlktdr/HeadTracker#26]
BLE has firmware 0.72 loaded...tried to connect using .90 GUI to update and got "unable to determine board type" error.
Connecting with GUI .72 connects successfully.
Screenshots below.

Serial info screen shows:
`Connected to COM6
Trying to connect to NANO33BLE 
GUI: {"Cmd":"FW"}� 
HT: FW Requested 
Trying to connect to BNO055 
GUI: $HARD 
GUI: $VERS 
Disconnecting from COM6
`

![GUI 0 72](https://user-images.githubusercontent.com/65918321/112886918-8e35f500-90a0-11eb-880e-6d8710a7a78d.jpg)
![GUI 0 90](https://user-images.githubusercontent.com/65918321/112886920-8ece8b80-90a0-11eb-8f95-51e9b942be89.jpg)

**Comment by kevin-kevjan** [comment]
**Upgrading firmware on board to Ver 0.90 does resolve issue.**

**Comment by dlktdr** [comment]
Since 0.8 old firmware will not connect due to the addition of CRC checking of data. 

Always try to be sure you are on a 0.9x firmware and a 0.9x GUI, or a 0.8x Gui and 0.8x FW to be sure of compatibility
