### ISSUE TITLE
Correction on the SBUS-Output page

### ISSUE THREAD

**Issue by codegrue** [dlktdr/HeadTracker#31]
Regarding this page: https://github.com/dlktdr/HeadTracker/wiki/SBUS-Output

I found the steps to set up the TX16S (Open TX) to be inaccurate. 

1) You do not need the SC switch special function
2) instead, In MODEL -> MODEL SETUP -> INPUTS, you set an input for the channel you want (e.g. 9) and set the source to the trainer input (e.g. TR5)

So for example:

- Input, Channel 9, Source=TR5 (Tilt)
- Input, Channel 10, Source=TR6 (Roll)
- Input, Channel 11, Source=TR7 (Pan)

That's all that's required to get the head tracker data into an input.

Note: Could not find a way to contact Rotorman/Risto directly to suggest an update.

**Comment by dlktdr** [comment]
Modified to clarify this method of setting Trainer under special functions is just an easy way to see the all the trainer data.
