### ISSUE TITLE
Can I use a type-c to micro usb cable to power the Arduino Nano board through the USB Type-C port on the DJI Goggle？

### ISSUE THREAD

**Issue by donne1226** [dlktdr/HeadTracker#33]

**Comment by dlktdr** [comment]
Doesn't look like it. Found this on a Forum

https://forum.dji.com/thread-180554-1-1.html#:~:text=It%20doesn't.,with%20a%20USB%2DC%20plug.

**Comment by donne1226** [comment]
> Doesn't look like it. Found this on a Forum
> 
> https://forum.dji.com/thread-180554-1-1.html#:~:text=It%20doesn't.,with%20a%20USB%2DC%20plug.

thanks a lot, I will find another way
