### ISSUE TITLE
jeti users

### ISSUE THREAD

**Issue by jag3957** [dlktdr/HeadTracker#36]
possible connections modes for jeti users. PPM TX physical connection NOT must be more that 3.2 to 4.2 max 1A. arduino is 5 to 20 volts.

**Comment by dlktdr** [comment]
Not sure I understand what you asking

Are you using Arduino nano 33 BLE? It is only 3.3v on the PPM output pin.

Input voltage to the board is 5-20 which is unrelated to the IO pins. There is a regulator on the board that drops that voltage to 3.3 for everything

**Comment by jag3957** [comment]
so I can connect directly to pins 1,2,3 in the tx?
<img width="572" alt="Screen Shot 2021-06-11 at 09 45 49" src="https://user-images.githubusercontent.com/85746687/121696534-29344d80-ca9a-11eb-91ae-c62991815886.png">

**Comment by dlktdr** [comment]
As long as you using the Arduino nano 33 BLE. Not the BN0055 project on this site too. Then yes you can direct connect them they are 3.3v in and out.

**Comment by jag3957** [comment]
thank you too much. yes I found in amazon. I will try to make it wireless that is my dream LOL. jeti have a wireless trainer mode , they connect a second TX to a primary TX and sent finally to receiver using just the primary TX. I am dreaming to connect the nano 33 to a jeti receiver and configure the pin in the receiver to receive and sent those commands to primary TX finally sent it to aircraft receiver in the plane. you know if can do that?

**Comment by dlktdr** [comment]
Not too sure. Will have to try.
