### ISSUE TITLE
Analog Read Reference Voltage

### ISSUE THREAD

**Issue by dlktdr** [dlktdr/HeadTracker#37]
Get it set to VDD, currently using internal reference, causing voltages readings to max out at 0.6v

**Comment by rotorman** [comment]
Possibly the following PDF of Nordic can help: Sec. 6.23.2 (page 379) and 6.23.9.20 (page 394):
https://infocenter.nordicsemi.com/pdf/nRF52840_PS_v1.2.pdf
The solution could be to set the ADC reference to VDD/4 and gain of 1/4.

**Comment by dlktdr** [comment]
Think I tried that but I'll try again. 
I'll have to dig deeper into the Zephyr Analog Nordic Driver., if set to the internal it works as expected, set to any other source no reads..

Just making a list of known issues for now, working on getting the zephyr version release ready to go. So people know what doesn't work.

**Comment by dlktdr** [comment]
Completed.

**Comment by dlktdr** [comment]
Posted in 2.01
