### ISSUE TITLE
"TLS Initialization failed"

### ISSUE THREAD

**Issue by dlktdr** [dlktdr/HeadTracker#4]
Issue trying to load firmware. Probably couldn't find the OpenSSL library I packaged with it. Need some more info on the windows version. Maybe I'll switch to a 32bit build for compatibility

**Comment by kevin-kevjan** [comment]
in V0.41 and using Win 10 home (below) get "TLS Initialization failed" error when clicking on Upload Firmware menu option.
Step to reproduce: Unzip file to dir on desktop and run HeadTracker.exe. Click "Upload Firmware".

![Screenshot 2021-02-02 211000](https://user-images.githubusercontent.com/65918321/107104346-3c36c880-67ef-11eb-9617-889f5cb8493f.jpg)

Edition	Windows 10 Home
Version	20H2
Installed on	‎2/‎4/‎2021
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by jreise-d** [comment]
Same here. Win10 Pro 64bit Version 20H2. Same on another computer with Version 2004.
I have tested 0.5 and 0.41.
![ArduinoBLE_Error](https://user-images.githubusercontent.com/46974509/107551157-34519c80-6bd2-11eb-9392-2b00cf57225b.jpg)
A strange thing: After the error appears, the file firmwares.ini in the directory HeadTrackerGUI_x64.-.V0.5 is emptied, so it has 0 bytes instead of 2kB

**Comment by dlktdr** [comment]
The firmwares.ini file is the one that gets downloaded from the online source. Since it can't download I'm not surprised it's gone.

I'll try to hard link the SSL libraries in the code rather than shipping the .dLL's to see if it makes a difference.

In the meantime can you install http://slproweb.com/products/Win32OpenSSL.html
Should be the "Win64 OpenSSL v1.1.1i Light package"

**Comment by jreise-d** [comment]
thank you so much! With the 32bit version it works

**Comment by dlktdr** [comment]
Please check out the 0.7 release. I'm going to go to a 32 bit from here on out.

**Comment by dlktdr** [comment]
I've found the root cause of this. OpenSSL needs the Microsoft Visual C++ redistributable 2015, which many computers already have installed but not all. 

Please install https://www.microsoft.com/en-ca/download/details.aspx?id=48145

I've included the missing file in the 0.71 release file https://github.com/dlktdr/HeadTracker/blob/master/gui/bin/HeadTrackerGUI_x64%20-%20V0.71.zip

Also cancel the 32bit idea. That wasn't a problem.
