### ISSUE TITLE
Possible Issue with desktop application

### ISSUE THREAD

**Issue by CorruptName** [dlktdr/HeadTracker#44]
I updated to the new version 2.0 last night and it seems to be working great.
When i went to update the firmware through the application I selected "Online V2.0" and there is no firmware available. I had to select "Shipped Firmware" before the listbox would fill. Just thought you should know. Once you select Shipped, you can then select Online and it will work (it seems)

![Firmware Loader 6_14_2021 12_47_36 PM](https://user-images.githubusercontent.com/25914159/121929125-e038ff00-cd0e-11eb-8e28-09a322f045ba.png)

Thanks again for your awesome work.

**Comment by dlktdr** [comment]
Good to know. I'll see if I can reproduce it

**Comment by dlktdr** [comment]
Haven't been able to reproduce here. Maybe a network connection issue startup?

Going to close this out. Let me know if I need to re-open
