### ISSUE TITLE
InitSensors after power up 

### ISSUE THREAD

**Issue by Ziege-One** [dlktdr/HeadTracker#7]
Hello,
if I power up my tracker the BNO055 will not INT. 
If I made reset it will work.
So I test a little with the INT here is my solution
```
    Wire.begin();               // Start I2C
    delay(200);                          <----------------------- 
    CheckI2CPresent();
```
A short delay between Wire.begin and CheckI2CPresent
with kind regards
Frank

**Comment by dlktdr** [comment]
I've added it to version 0.42
