### ISSUE TITLE
Bluetooth trainer issue

### ISSUE THREAD

**Issue by Iamyahodfpv** [dlktdr/HeadTracker#79]
Hello, i have the arduino board paired with my qx7s but cannot get any response from it. outputs are set up and still nothing

**Comment by dlktdr** [comment]
Which firmware are you using? Firmware less than 2.0 wouldn't work with the CC2540 module in some radios. Will connect but never receive data.
You have the channel outputs in the GUI for the nano set to something other than off?
Do you hear "trainer signal recovered/lost" on the radio and lost when the Nano is turned on and off? If you hear this it's sending data and probably just a configuration issue somewhere Radio or Headtracker GUI.

**Comment by Iamyahodfpv** [comment]
I am using .92 for the firmware. i couldn't get the newer firmware to flash

**Comment by Iamyahodfpv** [comment]
i have the channel outputs to 7 and 8

**Comment by Iamyahodfpv** [comment]
I tried going from .92 to 2.11 and it says programming failed

**Comment by dlktdr** [comment]
Yeah you probably have a CC2540 bluetooth module, will need v2..

As soon as it says "waiting for programming port" try double tap the white button quickly and wait. This will force bootloader mode.

**Comment by Iamyahodfpv** [comment]
I tried to double tap the white button as soon as it said that and it still says programming failed

**Comment by dlktdr** [comment]
Try this, Use the 0.92 GUI. 
Download this file https://github.com/dlktdr/HeadTracker/blob/master/firmware/bin/BLE%20v2.11.bin
Choose upload firmware, choose a local file and try selecting this downloaded file. Double tap, Refresh the ports and try uploading.

If it uploads see if you can then use the 2.1GUI

Have you tried other USB cords too?

**Comment by Iamyahodfpv** [comment]
that worked, what bluetooth setting do i need to use in the gui?

**Comment by dlktdr** [comment]
You want "head mode"
https://headtracker.gitbook.io/head-tracker/settings/gui-settings/bluetooth

**Comment by Iamyahodfpv** [comment]
And just set the receiver channels in the gui?

**Comment by Iamyahodfpv** [comment]
I set the receiver channels and it works! Thank you for the help!

**Comment by dlktdr** [comment]
Yes just choose the channels you want the Bluetooth data to be output on the main screen (tilt/roll/pan) https://headtracker.gitbook.io/head-tracker/settings/gui-settings/tilt-roll-pan
You can only use Ch1-8 over Bluetooth.

If you need more help setting up be sure to sign into the Discord chat too.

Great to hear!

**Comment by Iamyahodfpv** [comment]
I have one last question. I have the head tracker all set up but if I tilt the goggles too far up the servo resets to the bottom. What could be causing that?

**Comment by dlktdr** [comment]
There is only 180 degrees of tilt available. If you go over 90 up or down thinks its upside down and flips the output. A eurler angle thing.. If you have the board mounted in a not flat orientation, you're going to lose some of this tilt range when you center it.

Take a look at the video on rotation here If you set this right, there should be more than enough range without it rolling over.

https://headtracker.gitbook.io/head-tracker/settings/gui-settings/general
