### ISSUE TITLE
nano33ble version does not work wirelessly if ppm out to Digital Pins is disabled.

### ISSUE THREAD

**Issue by SilentZen** [dlktdr/HeadTracker#8]
nano33ble version does not work wirelessly if ppm out to Digital Pins is disabled.

**Comment by dlktdr** [comment]
Your right. Thank you. It's been fixed 
[Diff](https://github.com/dlktdr/HeadTracker/commit/4c82d16a6816bdfdc4fbc0b1f15dd14292ed10f8)

I will add to the next release. I'm working on making PPM output more stable I will add to that one

**Comment by SilentZen** [comment]
Thanks, much appreciated.
