### ISSUE TITLE
Cant bind it by Jack FRSKY Taranis X9 lite

### ISSUE THREAD

**Issue by denberan** [dlktdr/HeadTracker#81]
Cant bind it with my taranis x9d lite. I want to bind it with the Jack, but it doesnt work. chaneloutputs on the ht are fine. dont know what to do. need help please

**Comment by dlktdr** [comment]
Check that the PPM output pin and ground are properly connected. Also the correct PPM output pin is selected in the GUI. Can try inverted too incase your radio is setup to pick up inverted. Can post some photos of the wiring and settings if your not sure. Make sure radio is on Master/Jack for trainer, you should hear "Trainer Signal Lost" / "Recovered" on connections if the wiring and link is okay.

You might want to check you have the most recent firmware, I know there were some issues with some trainer connections on some older versions https://github.com/opentx/opentx/issues/8670.
