### ISSUE TITLE
RC Wireless Controls

### ISSUE THREAD

**Issue by skythj** [dlktdr/HeadTracker#85]
Hello, hope to make a wireless version, you know, many controls for RC Control don't have a coach interface now, so I don't seem to know what to do. . .

**Comment by dlktdr** [comment]
Do you mean your Radio doesn't have a trainer port?

You could use a PPM supported transmitter module like Crossfire and a separate receiver for the servos is an option. https://www.team-blacksheep.com/products/prod:crossfire_tx

Or can pass PPM into a 4in1 module https://rotorev.com/content/JP4IN1Manual.pdf that could be bound to many receivers.

If this is what you mean..
