### ISSUE TITLE
Unable to determine board type

### ISSUE THREAD

**Issue by dlktdr** [dlktdr/HeadTracker#90]
Note: You will also see this message if you have not uploaded firmware to the board on every version (Choose Firmware -> Upload Firmware) first.

There is a serial issue where the initial firmware request message is cut short when sent from the board causing the GUI to to be able to tell what try of board is attached.

For now just reconnect. Pertains to version 2.2 only here.

This was caused by the addition of the GIT sha to the firmware.

Edit: Underlying issues with serial CDC, looking into Zephyr's async

**Comment by gcmcnutt** [comment]
I have also had success with requesting the FW command twice at startup.  e.g. the first one is more of a buffer flush in the client PC and the second one is for real data.
