### ISSUE TITLE
Need BT connected LED on output pin for integration inside BDI digidapter

### ISSUE THREAD

**Issue by bvanderhoek** [dlktdr/HeadTracker#93]
I am building the head nano BLE33 into a BDI digidapter, but barely fits inside next to an analog VRX
I want the HT to switch power on the BDI activation switch, that will work but there is no way i can see if it is connected. 
Request is to add an active high output (e.g I/O pin D3) for an external LED to show BT-connected.

**Comment by dlktdr** [comment]
You can use D13 as an LED output. It's hooked up to the Yellow one on the board. You can parallel another, hook it up the same as the one shown here with same resistor.

![Screenshot 2022-05-30 082956](https://user-images.githubusercontent.com/281145/171023748-abe3c992-c200-429c-96e3-59f27d26f426.png)

![Screenshot 2022-05-30 083404](https://user-images.githubusercontent.com/281145/171024417-52f3fd5f-6864-40c3-a3e5-dfe6cc7d970d.png)

In V2.2 the LED changes modes if the BT is connected or not. Have a few bugs left to fix before I can release it but if you want to try in it's current state it's here. 

[HT2.2Beta](https://github.com/dlktdr/HeadTracker/files/8791268/HT22Beta.zip) Replace the .exe with the one from V2.1. Choose upload from local to write the firmware included

FYI Gyro calibration is done on boot. Set the board down so it's completely still until the red light goes out. The on board gyro calibration will change so the outputs aren't disabled if the user skips this step, using the previous values instead.
